name: Denopendabot

description: Keeps your Deno projects up-to-date

inputs:
  token:
    description: Access token authorized to run workflows
    required: true
    default: ${{ github.token }}

  user-token:
    description: Personal access token authorized to update workflows
    required: false

  repository:
    description: Repository to update dependencies
    required: true
    default: ${{ github.repository }}

  base-branch:
    description: Branch to update
    required: true
    default: main

  working-branch:
    description: Working branch for Denopendabot
    required: true
    default: denopendabot
  
  options:
    description: Other options passed to the CLI
    required: false

runs:
  using: composite

  steps:
    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.26.2 # @denopendabot denoland/deno

    - name: Run Denopendabot
      run: >
        deno run -q --allow-env --allow-net
        https://deno.land/x/denopendabot@1.0.0/main.ts
        ${{ inputs.repository }}
        --base ${{ inputs.base-branch }}
        --branch ${{ inputs.working-branch }}
        ${{ inputs.token && format('--token {0}', inputs.token) }}
        ${{ inputs.user-token && format('--user-token {0}', inputs.user-token) }}
        ${{ inputs.options }}
      shell: bash

branding:
  icon: 'refresh-cw'
  color: 'gray-dark'
