name: CI/CD

on:
  push:
    branches: 
      - main
    paths:
      - '**.ts'
      - '**.yml'
  workflow_dispatch:

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml
    secrets: inherit

  deploy-staging:
    name: Staging Deploy
    needs: test
    if: github.repository_owner == 'hasundue'
    uses: ./.github/workflows/deploy.yml
    with:
      deployment: staging
    secrets: inherit

  integration:
    name: Integration
    needs: deploy-staging
    uses: ./.github/workflows/integration.yml
    secrets: inherit

  release:
    name: Release
    needs: integration
    uses:  ./.github/workflows/release.yml
    secrets: inherit

  deploy-production:
    name: Deploy
    needs: release
    if: ${{ needs.release.outputs.released }}
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      deployment: production
